# ansible-galaxy install -r requirements.yaml
# ansible-playbook -b docker.yaml -i <inventory file>
---
- name: Prerun checks
  hosts: all
  roles:
    - role: tixsalvador3.uptime
    - role: tixsalvador3.docker
